### ISSUE TITLE
[pcie_core] [dbe_bpm_dsp] XDC files references nets Vivado can't find

### ISSUE THREAD

**Issue by aylons** [lnls-dig/bpm-gw#46]
_PROBLEM:_ Some constraints in pcie_core.xdc and dbe_bpm_dsp.xdc are commented and marked as FIXME because Vivado can' t find the proper nets after migration from ISE. These constraints do not prevent proper operation of the core, but may be leading to inefficiencies during implementation.

_Possible Solution:_ This is probably caused by the nets being differently referenced in Vivado due to hierarchy. Finding a proper way to reference the same net using the new XDC features should solve the problem.

**Comment by lerwys** [comment]
The referenced constraints no longer exist
