### ISSUE TITLE
[Interlock] Improvements

### ISSUE THREAD

**Issue by lerwys** [lnls-dig/bpm-gw#83]
Suggestions from operations:

- [x] Fix current interlock status. This is not readable as the FPGA generates a shot pulse. We need to stretch it so a software can read.
- [x] Check angular interlock calculation. We need to use `downstream position` - `upstream position`
- [x] Add calculated translation/angular register so we can better debug what is being done inside the FPGA
- [x] #84
- [x] Check what interlocks are actually being `masked`by the `enable bits

**Comment by danielot** [comment]
Should we close this issue? All tasks have been done.
